# Generated by Django 4.1.7 on 2023-05-05 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New directory', max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='creation date')),
                ('alive', models.BooleanField(default=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='change date')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dir_browse.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New directory', max_length=200)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='creation date')),
                ('alive', models.BooleanField(default=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='delete date')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='change date')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dir_browse.user')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dir_browse.directory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
