# Generated by Django 4.1.7 on 2023-05-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dir_browse.directory'),
        ),
    ]
