# Generated by Django 4.1.7 on 2023-05-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0004_optimization_processor_standard_compilationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilationsettings',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dir_browse.processor'),
        ),
        migrations.CreateModel(
            name='DependantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir_browse.processor')),
            ],
        ),
    ]
