# Generated by Django 4.1.7 on 2023-05-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0005_compilationsettings_processor_dependantoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimization',
            name='name',
        ),
    ]
