# Generated by Django 4.1.7 on 2023-05-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0006_remove_optimization_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Optimization',
        ),
    ]
