# Generated by Django 4.1.7 on 2023-05-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0008_optimization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DependantOption',
        ),
    ]
