# Generated by Django 4.1.7 on 2023-05-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dir_browse', '0009_delete_dependantoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dir_browse.processor')),
            ],
        ),
    ]
